name: Save Coordinates

on:
  workflow_dispatch:
    inputs:
      coordinates:
        description: 'Polygon coordinates'
        required: true

jobs:
  save-coordinates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Save Coordinates
        run: |
          echo "${{ github.event.inputs.coordinates }}" > polygon_coordinates.json
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add polygon_coordinates.json
          git commit -m "Save polygon coordinates"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
